// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/app/secret/presenter/http/grpc/proto/secret.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SecretRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	ExpireAfterViews     int64    `protobuf:"varint,2,opt,name=expireAfterViews,proto3" json:"expireAfterViews,omitempty"`
	ExpireAfter          int64    `protobuf:"varint,3,opt,name=expireAfter,proto3" json:"expireAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretRequest) Reset()         { *m = SecretRequest{} }
func (m *SecretRequest) String() string { return proto.CompactTextString(m) }
func (*SecretRequest) ProtoMessage()    {}
func (*SecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_782b125d2565c724, []int{0}
}

func (m *SecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretRequest.Unmarshal(m, b)
}
func (m *SecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretRequest.Marshal(b, m, deterministic)
}
func (m *SecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretRequest.Merge(m, src)
}
func (m *SecretRequest) XXX_Size() int {
	return xxx_messageInfo_SecretRequest.Size(m)
}
func (m *SecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretRequest proto.InternalMessageInfo

func (m *SecretRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *SecretRequest) GetExpireAfterViews() int64 {
	if m != nil {
		return m.ExpireAfterViews
	}
	return 0
}

func (m *SecretRequest) GetExpireAfter() int64 {
	if m != nil {
		return m.ExpireAfter
	}
	return 0
}

type HashRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashRequest) Reset()         { *m = HashRequest{} }
func (m *HashRequest) String() string { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()    {}
func (*HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_782b125d2565c724, []int{1}
}

func (m *HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashRequest.Unmarshal(m, b)
}
func (m *HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashRequest.Marshal(b, m, deterministic)
}
func (m *HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRequest.Merge(m, src)
}
func (m *HashRequest) XXX_Size() int {
	return xxx_messageInfo_HashRequest.Size(m)
}
func (m *HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashRequest proto.InternalMessageInfo

func (m *HashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type SecretResponse struct {
	Hash                 string               `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SecretText           string               `protobuf:"bytes,2,opt,name=secretText,proto3" json:"secretText,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	RemainingViews       int64                `protobuf:"varint,5,opt,name=remainingViews,proto3" json:"remainingViews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SecretResponse) Reset()         { *m = SecretResponse{} }
func (m *SecretResponse) String() string { return proto.CompactTextString(m) }
func (*SecretResponse) ProtoMessage()    {}
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_782b125d2565c724, []int{2}
}

func (m *SecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretResponse.Unmarshal(m, b)
}
func (m *SecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretResponse.Marshal(b, m, deterministic)
}
func (m *SecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretResponse.Merge(m, src)
}
func (m *SecretResponse) XXX_Size() int {
	return xxx_messageInfo_SecretResponse.Size(m)
}
func (m *SecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretResponse proto.InternalMessageInfo

func (m *SecretResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SecretResponse) GetSecretText() string {
	if m != nil {
		return m.SecretText
	}
	return ""
}

func (m *SecretResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SecretResponse) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *SecretResponse) GetRemainingViews() int64 {
	if m != nil {
		return m.RemainingViews
	}
	return 0
}

func init() {
	proto.RegisterType((*SecretRequest)(nil), "proto.SecretRequest")
	proto.RegisterType((*HashRequest)(nil), "proto.HashRequest")
	proto.RegisterType((*SecretResponse)(nil), "proto.SecretResponse")
}

func init() {
	proto.RegisterFile("internal/app/secret/presenter/http/grpc/proto/secret.proto", fileDescriptor_782b125d2565c724)
}

var fileDescriptor_782b125d2565c724 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xff, 0xfd, 0x03, 0x4d, 0x18, 0x22, 0x31, 0x13, 0x35, 0x0d, 0x07, 0xc5, 0x1e, 0x0c,
	0xf1, 0xd0, 0x4d, 0xf0, 0xa0, 0xf1, 0x46, 0x3c, 0xe8, 0xb9, 0x12, 0xef, 0x0b, 0x0e, 0xed, 0x26,
	0xd0, 0xae, 0xbb, 0xd3, 0xc8, 0xc7, 0xf5, 0xa3, 0x18, 0x76, 0x5b, 0xad, 0xa8, 0xf1, 0xd4, 0xee,
	0xaf, 0xef, 0xcd, 0xbc, 0xbe, 0x85, 0x5b, 0x55, 0x30, 0x99, 0x42, 0xae, 0x85, 0xd4, 0x5a, 0x58,
	0x5a, 0x1a, 0x62, 0xa1, 0x0d, 0x59, 0xda, 0x71, 0x91, 0x33, 0x6b, 0x91, 0x19, 0xbd, 0x14, 0xda,
	0x94, 0x5c, 0xd6, 0x82, 0xc4, 0x1d, 0xb0, 0xe7, 0x1e, 0xa3, 0xb3, 0xac, 0x2c, 0xb3, 0x35, 0x79,
	0xc5, 0xa2, 0x5a, 0x09, 0x56, 0x1b, 0xb2, 0x2c, 0x37, 0xda, 0xeb, 0xe2, 0x0a, 0x0e, 0x1e, 0x9d,
	0x2f, 0xa5, 0x97, 0x8a, 0x2c, 0xe3, 0x09, 0x84, 0x7e, 0x50, 0x14, 0x8c, 0x83, 0x49, 0x3f, 0xad,
	0x4f, 0x78, 0x09, 0x87, 0xb4, 0xd5, 0xca, 0xd0, 0x6c, 0xc5, 0x64, 0x9e, 0x14, 0xbd, 0xda, 0xe8,
	0xff, 0x38, 0x98, 0x74, 0xd2, 0x6f, 0x1c, 0xc7, 0x30, 0x68, 0xb1, 0xa8, 0xe3, 0x64, 0x6d, 0x14,
	0x9f, 0xc3, 0xe0, 0x41, 0xda, 0xbc, 0x59, 0x8a, 0xd0, 0xcd, 0xa5, 0xcd, 0xeb, 0x95, 0xee, 0x3d,
	0x7e, 0x0b, 0x60, 0xd8, 0x44, 0xb3, 0xba, 0x2c, 0x2c, 0xfd, 0x24, 0xc3, 0x53, 0x00, 0x9f, 0x70,
	0x4e, 0x5b, 0x76, 0x89, 0xfa, 0x69, 0x8b, 0xe0, 0x0d, 0xf4, 0x97, 0x86, 0x24, 0xd3, 0xf3, 0x8c,
	0x5d, 0x92, 0xc1, 0x74, 0x94, 0xf8, 0x56, 0x92, 0xa6, 0x95, 0x64, 0xde, 0xb4, 0x92, 0x7e, 0x8a,
	0x77, 0x4e, 0x1f, 0xd9, 0xce, 0x38, 0xea, 0xfe, 0xed, 0xfc, 0x10, 0xe3, 0x05, 0x0c, 0x0d, 0x6d,
	0xa4, 0x2a, 0x54, 0x91, 0xf9, 0xa6, 0x7a, 0xae, 0x82, 0x3d, 0x3a, 0xad, 0x20, 0xf4, 0x7f, 0x88,
	0xd7, 0x10, 0xde, 0xb9, 0xc5, 0x78, 0xe4, 0x67, 0x27, 0x5f, 0x6e, 0x65, 0x74, 0xbc, 0x47, 0x7d,
	0x21, 0xf1, 0x3f, 0x9c, 0x42, 0xe7, 0x9e, 0x18, 0xb1, 0xfe, 0xde, 0x2a, 0xf5, 0x57, 0xcf, 0x22,
	0x74, 0xfc, 0xea, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x78, 0x9b, 0x51, 0x60, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SecretClient is the client API for Secret service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretClient interface {
	Create(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error)
	Get(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*SecretResponse, error)
}

type secretClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretClient(cc grpc.ClientConnInterface) SecretClient {
	return &secretClient{cc}
}

func (c *secretClient) Create(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, "/proto.Secret/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretClient) Get(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*SecretResponse, error) {
	out := new(SecretResponse)
	err := c.cc.Invoke(ctx, "/proto.Secret/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServer is the server API for Secret service.
type SecretServer interface {
	Create(context.Context, *SecretRequest) (*SecretResponse, error)
	Get(context.Context, *HashRequest) (*SecretResponse, error)
}

// UnimplementedSecretServer can be embedded to have forward compatible implementations.
type UnimplementedSecretServer struct {
}

func (*UnimplementedSecretServer) Create(ctx context.Context, req *SecretRequest) (*SecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSecretServer) Get(ctx context.Context, req *HashRequest) (*SecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterSecretServer(s *grpc.Server, srv SecretServer) {
	s.RegisterService(&_Secret_serviceDesc, srv)
}

func _Secret_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Secret/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).Create(ctx, req.(*SecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Secret_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Secret/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServer).Get(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Secret_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Secret",
	HandlerType: (*SecretServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Secret_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Secret_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/secret/presenter/http/grpc/proto/secret.proto",
}
